routes/web.php
<?php
Route::redirect('/', 'admin/home');

Auth::routes(['register' => false]);

// Change Password Routes...
Route::get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
Route::patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');
Auth::routes();

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/lang/{locale}', 'Admin\UsersController@lang');
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::delete('permissions_mass_destroy', 'Admin\PermissionsController@massDestroy')->name('permissions.mass_destroy');
    Route::resource('roles', 'Admin\RolesController');
    Route::delete('roles_mass_destroy', 'Admin\RolesController@massDestroy')->name('roles.mass_destroy');
    Route::resource('users', 'Admin\UsersController');
    Route::delete('users_mass_destroy', 'Admin\UsersController@massDestroy')->name('employees.mass_destroy');
    Route::resource('employees' , 'Admin\EmployeesController');
    Route::delete('employees_mass_destroy', 'Admin\EmployeesController@massDestroy')->name('employees.mass_destroy');
});

app/Employee.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
/**
 * Class User
 *
 * @package App
 * @property string $name1
 * @property string $name2
 * @property string $last_name1
 * @property string $last_name2
*/
class Employee extends Model
{
    protected $fillable = ['name1','name2','last_name1','last_name2', 'type_document', 'num_document', 'state'];


}

app/Http/Controllers/API/EmployeesController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\API\BaseController as BaseController;
use App\Employee;
use Validator;
use App\Http\Resources\Employee as WebResource;

class EmployeesController extends BaseController
{

    public function index()
    {
        $employees = Employee::all();
        
        return $this->sendResponse(WebResource::collection($employees), 'Webs retrieved successfully.');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();


        $validator = Validator::make($input, [
            'name' => 'required',
            'URL' => 'required'
        ]);

        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());       
        }

        $employee = Employee::create($input);

        return $this->sendResponse(new WebResource($employee), 'Web created successfully.');
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $employee = Employee::find($id);

        if (is_null($employee)) {
            return $this->sendError('Web not found.');
        }

        return $this->sendResponse(new WebResource($employee), 'Web retrieved successfully.');
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Employee $employee)
    {
        $input = $request->all();

        $validator = Validator::make($input, [
            'name' => 'required',
            'URL' => 'required'
        ]);

        if($validator->fails()){
            return $this->sendError('Validation Error.', $validator->errors());       
        }

        $employee->name = $input['name'];
        $employee->URL = $input['URL'];
        $employee->save();

        return $this->sendResponse(new WebResource($employee), 'Web updated successfully.');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return $this->sendResponse([], 'Web deleted successfully.');
    }
}

app/Http/Controllers/Admin/EmployeesController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Employee;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Gate;
use App\Http\Requests\Admin\StoreEmployeesRequest;
use App\Http\Requests\Admin\UpdateEmployeesRequest;

class EmployeesController extends Controller
{
      /**
     * Display a listing of Employee.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        $employees = Employee::all();

        return view('admin.employees.index', compact('employees'));
    }

    /**
     * Show the form for creating new Employee.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }

        if(auth()->user()->status == 0){
            return abort(401);
        }
        return view('admin.employees.create');
    }

    /**
     * Store a newly created Employee in storage.
     *
     * @param  \App\Http\Requests\StoreEmployeesRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreEmployeesRequest $request)
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        $employee = Employee::create($request->all());

        return redirect()->route('admin.employees.index');
    }


    /**
     * Show the form for editing Employee.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        return view('admin.employees.edit', compact('employee'));
    }

    /**
     * Update Employee in storage.
     *
     * @param  \App\Http\Requests\UpdateEmployeesRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeesRequest $request, Employee $employee)
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        $employee->update($request->all());

        return redirect()->route('admin.employees.index');
    }

    public function show(Employee $employee)
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        return view('admin.employees.show', compact('employee'));
    }

    /**
     * Remove Employee from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        $employee->delete();

        return redirect()->route('admin.employees.index');
    }

    /**
     * Delete all selected Employee at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('permiso_administrado')) {
            return abort(401);
        }
        if(auth()->user()->status == 0){
            return abort(401);
        }
        Employee::whereIn('id', request('ids'))->delete();

        return response()->noContent();
    }
}

resources/views/admin/employees/create.blade.php
@extends('layouts.admin')
@section('content')
{{ app()->setLocale(session('locale')) }}
<div class="card">
    <div class="card-header">
        {{ trans('Crear') }} {{ trans('Empleado') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.employees.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('name1') ? 'has-error' : '' }}">
                <label for="name1">{{ __('content.nombre') }} 1*</label>
                <input type="text" id="name1" name="name1" class="form-control" value="{{ old('name1', isset($employee) ? $employee->name1 : '') }}" required>
            </div>

            <div class="form-group {{ $errors->has('name2') ? 'has-error' : '' }}">
                <label for="name2">{{ __('content.nombre') }} 2*</label>
                <input type="text" id="name2" name="name2" class="form-control" value="{{ old('name2', isset($employee) ? $employee->name2 : '') }}" required>
            </div>

            <div class="form-group {{ $errors->has('last_name1') ? 'has-error' : '' }}">
                <label for="last_name1">{{ __('content.apellido') }} 1*</label>
                <input type="text" id="last_name1" name="last_name1" class="form-control" value="{{ old('last_name1', isset($employee) ? $employee->last_name1 : '') }}" required>
            </div>

            <div class="form-group {{ $errors->has('last_name2') ? 'has-error' : '' }}">
                <label for="last_name2">{{ __('content.apellido') }} 2*</label>
                <input type="text" id="last_name2" name="last_name2" class="form-control" value="{{ old('last_name2', isset($employee) ? $employee->last_name2 : '') }}" required>
            </div>

            <div class="form-group {{ $errors->has('type_document') ? 'has-error' : '' }}">
                <label for="type_document">{{ __('content.tipo_de_documento') }}*</label>
                <input type="text" id="type_document" name="type_document" class="form-control" value="{{ old('type_document', isset($employee) ? $employee->type_document : '') }}" required>
            </div>

            <div class="form-group {{ $errors->has('num_document') ? 'has-error' : '' }}">
                <label for="num_document">{{ trans('DNI') }}*</label>
                <input type="text" id="num_document" name="num_document" class="form-control" value="{{ old('num_document', isset($employee) ? $employee->num_document : '') }}" required>
            </div>

            <div class="form-group {{ $errors->has('state') ? 'has-error' : '' }}">
                <label for="state">{{ __('content.estado') }}*</label>
                <input type="text" id="state" name="state" class="form-control" value="{{ old('state', isset($employee) ? $employee->state : '') }}" required>
            </div>
            
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/employees/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.employee.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.employees.update", [$employee->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name1') ? 'has-error' : '' }}">
                <label for="name1">{{ trans('Primer Nombre') }}*</label>
                <input type="text" id="name1" name="name1" class="form-control" value="{{ old('name1', isset($employee) ? $employee->name1 : '') }}" required>
                @if($errors->has('name1'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name1') }}
                    </em>
                @endif

            </div>
            <div class="form-group {{ $errors->has('name2') ? 'has-error' : '' }}">
                <label for="name2">{{ trans('Segundo Nombre') }}*</label>
                <input type="text" id="name2" name="name2" class="form-control" value="{{ old('name2', isset($employee) ? $employee->name2 : '') }}" required>
                @if($errors->has('name2'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name2') }}
                    </em>
                @endif

            </div>

            <div class="form-group {{ $errors->has('last_name1') ? 'has-error' : '' }}">
                <label for="last_name1">{{ trans('Apellido Paterno') }}*</label>
                <input type="text" id="last_name1" name="last_name1" class="form-control" value="{{ old('last_name1', isset($employee) ? $employee->last_name1 : '') }}" required>
                @if($errors->has('last_name1'))
                    <em class="invalid-feedback">
                        {{ $errors->first('last_name1') }}
                    </em>
                @endif

            </div>


            <div class="form-group {{ $errors->has('last_name2') ? 'has-error' : '' }}">
                <label for="last_name2">{{ trans('Apellido Materno') }}*</label>
                <input type="text" id="last_name2" name="last_name2" class="form-control" value="{{ old('last_name2', isset($employee) ? $employee->last_name2 : '') }}" required>
                @if($errors->has('last_name2'))
                    <em class="invalid-feedback">
                        {{ $errors->first('last_name2') }}
                    </em>
                @endif

            </div>


            <div class="form-group {{ $errors->has('type_document') ? 'has-error' : '' }}">
                <label for="type_document">{{ trans('Tipo Documento') }}*</label>
                <input type="text" id="type_document" name="type_document" class="form-control" value="{{ old('type_document', isset($employee) ? $employee->type_document : '') }}" required>
                @if($errors->has('type_document'))
                    <em class="invalid-feedback">
                        {{ $errors->first('type_document') }}
                    </em>
                @endif

            </div>


            <div class="form-group {{ $errors->has('num_document') ? 'has-error' : '' }}">
                <label for="num_document">{{ trans('Identificación') }}*</label>
                <input type="text" id="num_document" name="num_document" class="form-control" value="{{ old('num_document', isset($employee) ? $employee->num_document : '') }}" required>
                @if($errors->has('num_document'))
                    <em class="invalid-feedback">
                        {{ $errors->first('num_document') }}
                    </em>
                @endif

            </div>


            <div class="form-group {{ $errors->has('state') ? 'has-error' : '' }}">
                <label for="state">{{ trans('Estado:') }}*</label>
                <input type="text" id="state" name="state" class="form-control" value="{{ old('state', isset($employee) ? $employee->state : '') }}" required>
                @if($errors->has('state'))
                    <em class="invalid-feedback">
                        {{ $errors->first('state') }}
                    </em>
                @endif

            </div>

            
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>


    </div>
</div>
@endsection

resources/views/admin/employees/index.blade.php
@extends('layouts.admin')
@section('content')
@can('permiso_administrado')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.employees.create") }}">
                {{ trans('Crear') }} 
            </a>
        </div>
    </div>
@endcan
{{ app()->setLocale(session('locale')) }}
<div class="card">
    <div class="card-header">
        {{ trans('Lista') }} {{ trans('Empleados') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('id') }}
                        </th>
                        <th>
                            {{ __('content.nombre_completo') }}
                        </th>
                        <th>
                            {{ __('content.documento_de_identidad') }}
                        </th>
                        <th>
                            {{ __('content.estado') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $key => $employee)
                        <tr data-entry-id="{{ $employee->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $employee->id ?? '' }}   
                            </td>
                            <td>
                                {{ $employee->name1 .' '.$employee->name2 . ' '.$employee->last_name1 .' '. $employee->last_name2  ?? '' }}
                            </td>
                            <td>
                                {{ $employee->num_document ?? '' }}
                            </td>
                            <td>
                                {{ $employee->state ?? '' }}
                            </td>
                            <td>
                                <a class="btn btn-xs btn-primary" href="{{ route('admin.employees.show', $employee->id) }}">
                                    {{ trans('global.view') }}
                                </a>

                                <a class="btn btn-xs btn-info" href="{{ route('admin.employees.edit', $employee->id) }}">
                                    {{ trans('global.edit') }}
                                </a>

                                <form action="{{ route('admin.employees.destroy', $employee->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                </form>

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>


    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('permiso_administrado')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.employees.mass_destroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  $('.datatable-User:not(.ajaxTable)').DataTable({ buttons: dtButtons })
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
        $($.fn.dataTable.tables(true)).DataTable()
            .columns.adjust();
    });
})

</script>
@endsection

resources/views/admin/employees/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('Ver') }} {{ trans('Empleado') }}
    </div>

    <div class="card-body">
        <div class="mb-2">
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('ID') }}
                        </th>
                        <td>
                            {{ $employee->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Nombre Completo') }}
                        </th>
                        <td>
                            {{ $employee->name1 .' '.$employee->name2 . ' '.$employee->last_name1 .' '. $employee->last_name2 }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('Tipo Documento') }}
                        </th>
                        <td>
                            {{ $employee->type_document }}
                        </td>
                    </tr>

                    <tr>
                        <th>
                            {{ trans('Documento de Identidad') }}
                        </th>
                        <td>
                            {{ $employee->num_document }}
                        </td>
                    </tr>


                    <tr>
                        <th>
                            {{ trans('Estado') }}
                        </th>
                        <td>
                            {{ $employee->state }}
                        </td>
                    </tr>


                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>


    </div>
</div>
@endsection